logout機能テストを作成いたしました。
Shogoohashi/SpringBootTest-mentee pull request #6
Opened 2023-04-05 01:46 UTC by Shogoohashi

2023-04-05 02:00 UTC, git-nori commented on src/test/java/com/example/controller/LogoutControllerTest.java
> +        @WithMockUser(roles = {"GENERAL"})
roleは不要

2023-04-05 02:02 UTC, git-nori commented on src/test/java/com/example/controller/LogoutControllerTest.java
> +                    );
認証状態の検証が抜けている

2023-04-10 07:42 UTC, git-nori requested changes

2023-04-10 07:42 UTC, git-nori commented on src/test/java/com/example/controller/LogoutControllerTest.java
> +        void testPostLogout() throws Exception {
ログイン状態でテストの実行はできている？

2023-04-11 01:45 UTC, Shogoohashi commented on src/test/java/com/example/controller/LogoutControllerTest.java
> +        void testPostLogout() throws Exception {
- ログイン状態でテストの実行はできている？
ログイン状態でできました。

- @WithMockUser（rolesは無視して）を付けるとどういう状態でテストが実行できる？
ログイン状態でのテストができます。そのため今回は場合、ログイン状態でないとログアウトができない想定のため
 @WithMockUserを付けて修正を行います。

2023-04-11 02:09 UTC, git-nori approved these changes

2023-04-11 02:09 UTC, git-nori commented on src/test/java/com/example/controller/LogoutControllerTest.java
> +        void testPostLogout() throws Exception {
その通り、いいね👍

2023-04-11 03:01 UTC, merged